### ISSUE TITLE
error in reduction.run()

### ISSUE THREAD

**Issue by educrot** [lgrcia/prose#1]
I got the following error during the reduction :

`RUN: Reduction:  18%|███▊                 | 199/1096 [01:27<06:24,  2.33files/s]WARNING: File may have been truncated: actual file length (2018364) is smaller than the expected size (8562240) [astropy.io.fits.file]`
`TypeError: buffer is too small for requested array`

when I open the corresponding file I get the following error in ds9: **`a SIGBUS or SIGSEGV error has been received`**

It looks like some files are corrupted.

**Comment by lgrcia** [comment]
This is quite outdated and was likely due to os or fitsio issue (could not reproduce)
