### ISSUE TITLE
Binned_white_function Issue

### ISSUE THREAD

**Issue by schackey** [lgrcia/prose#108]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/lgrcia/prose/issues?q=is%3Aissue).

## Question and/or Bug

In the 'binned_white_function' function in fluxes.py, I understand we set a number of bins, 'bins', and the size of the bins is calculated and stored in 'n'. When splitting a fluxes array in the 'compute' function, it looks to me like the array is split into 'n' equal sized parts, when it should be split into 'bins' equal sized parts. This probably won't make a huge difference most times (as mostly 'bins' and 'n' are comparable), but still a bit of a difference. What do you think?

## Additional context

def binned_white_function(x, bins: int = 12):
    # set binning idxs for white noise evaluation
    bins = np.min([x.shape[-1], bins])
    n = x.shape[-1] // bins
    idxs = np.arange(n * bins)

    def compute(f):
        return np.nanmean(
            np.nanstd(np.array(np.split(f.take(idxs, axis=-1), n, axis=-1)), axis=-1),
            axis=0,
        )

    return compute

**Comment by lgrcia** [comment]
Thanks for noticing that! Actually we do the opposite, we set the size of the bins in bins (number of points in one bin) and compute the number n of bins in the signal. Does that make more sense?

**Comment by schackey** [comment]
ah yes, absolutely makes sense, thank you! My brain just directly assumed 'bins' to be the amount of bins instead of bin size.

**Comment by lgrcia** [comment]
I think the name of the variable is dismissive. I will refactor it. Thanks for noticing!
