### ISSUE TITLE
CentroidBallet is hanging (tensforflow warning)

### ISSUE THREAD

**Issue by mathtimm** [lgrcia/prose#145]
When using Ballet as centroid algorithm, there is a warning from tensorflow (see image below) and the sequence is hanging, nothing is happening. 

<img width="1125" alt="image" src="https://github.com/lgrcia/prose/assets/61153722/ab056aac-6b57-4875-bc08-ff185edb096b">

**Comment by lgrcia** [comment]
I guess that's because you used a SequenceParallel, so the error is more difficult to trace. Can you try with a simple Sequence? (it's usually necessary to switch to a normal Sequence for proper debugging, I'll add that to the doc)

**Comment by mathtimm** [comment]
It works with a simple Sequence! I guess a warning would be welcome in the documentation to let people know Ballet is only operational for a Sequence. We can close the issue!

**Comment by lgrcia** [comment]
Many blocks are not tested/will not work with ParallelSequence. ParallelSequence was meant to be an experimental feature so I added that in its documentation rather than on specific blocks
