### ISSUE TITLE
Comparison between prose 2 and prose 3 

### ISSUE THREAD

**Issue by mathtimm** [lgrcia/prose#146]
I compared the photometry obtained with prose 2 and prose 3 a SPECULOOS dataset (TOI-6251 2023/09/23 for reference) and for a similar aperture size and the same comparison stars, the photometry is less good with prose 3. The sequence used is the same apart from the centroiding algorithm, but Ballet doesn't seem to work (see issue #145).

Prose 3 : aperture = 10.346601050103892 px, comps=[2,1]
![image](https://github.com/lgrcia/prose/assets/61153722/804d2d72-f591-46cf-b3fa-25fe2e26c544)
Prose 2 : aperture = 9.87536795795926 px, comps = [1,2]
![image](https://github.com/lgrcia/prose/assets/61153722/21828ead-4bda-48e3-b8cb-a1c6d8a766d3)

**Comment by lgrcia** [comment]
prose 2 and 3 are usually very comparable, as all algorithms used are the same and only the interface has changed. So I expect the centroiding algorithm to make most of the difference here, let's try to solve #145 before digging into this one

**Comment by lgrcia** [comment]
Did using `CentroidBallet` solved the issue?
