### ISSUE TITLE
ComputeTransformTwirl crashes for n>50 detected stars

### ISSUE THREAD

**Issue by mathtimm** [lgrcia/prose#160]
A sequence with `PointSourceDetection` with n = 150 stars followed by `ComputeTransformTwirl` systematically crashes if n>100 and gets significantly slow for n>80. This comes from the `solve` function which takes as input the whole of the detected stars and the computer cannot handle the size of the array. 

A fix could be selecting a smaller number of stars by adding an upper limit in the [`run` function.](https://github.com/lgrcia/prose/blob/78075d9740211f8e6a02151a49f041dd8cc5d066/prose/blocks/geometry.py#L192) 

For example at line 190 of prose/blocks/geometry.py: 

```
def run(self, image):
        if len(image.sources.coords) >= 5:
            if len(image.sources.coords) <= 50:
                result = self.solve(image.sources.coords)
            else:
                result = self.solve(image.sources.coords[:50])
            if result is not None:
                image.transform = AffineTransform(result).inverse
            else:
                image.discard = True
        else:
            image.discard = True
```

<img width="1003" alt="image" src="https://github.com/lgrcia/prose/assets/61153722/be13cbf6-dba2-4b1f-8768-d785d352a8ab">

**Comment by lgrcia** [comment]
Can I see how you instantiate the `ComputeTransformTwirl`?

**Comment by mathtimm** [comment]
Here is the sequence I use: 

```
photometry = Sequence(

[   calib_block,
blocks.Trim(),
blocks.PointSourceDetection(n=250),
blocks.Cutouts(21),
blocks.MedianEPSF(),
blocks.Moffat2D(ref),
blocks.LimitSources(),
blocks.ComputeTransformTwirl(ref),
blocks.AlignReferenceSources(ref,discard_tolerance=0.1),
blocks.CentroidQuadratic(),
blocks.AperturePhotometry(),
blocks.AnnulusBackground(),
blocks.GetFluxes(
    "fwhm",
    airmass=lambda im: im.header["AIRMASS"],
    dx=lambda im: im.transform.translation[0],
    dy=lambda im: im.transform.translation[1]
),
blocks.SelectiveStack(),
],
)
```

**Comment by mathtimm** [comment]
Never mind, I see why it was not working now. I had misunderstood which stars are used for the alignment:
-> The stars detected on the reference are the stars effectively used in the Aperture photometry blocks. 
-> The alignment is done using the newly detected stars on each frame, hence the number can be very small (like 10 or something).

**Comment by lgrcia** [comment]
Exactly! I usually put 15 or so. For the record, and you were completely right about it, the current version of *twirl* can go as high as 40 but more gets really heavy computationally. I should add that to the doc!
