### ISSUE TITLE
How to put a star out of consideration of Broeg2005()?

### ISSUE THREAD

**Issue by MouradGHACHOUI** [lgrcia/prose#24]
In some cases, the Broeg2005() gives "two" comparison stars as the best ones for differential photometry. One of the two stars presents some variations exactly during the transit time, which may have an impact one the transit signal. Is there any option to put that star out of Broeg2005() consideration? 
Thanks in advance ;)

**Comment by lgrcia** [comment]
This might still be relevant to version 3.0.0 in [Fluxes.autodiff](https://github.com/lgrcia/prose/blob/3.0.0/prose/fluxes.py#LL131C10-L131C10)

**Comment by lgrcia** [comment]
I think the best way to do that in prose >= 3.0.0 is to use the [`mask_stars`](https://prose.readthedocs.io/en/stable/md/generated/prose.Fluxes.mask_stars.html#prose.Fluxes.mask_stars) method prior to running [`autodiff`](https://prose.readthedocs.io/en/stable/md/generated/prose.Fluxes.autodiff.html#prose.Fluxes.autodiff)
