### ISSUE TITLE
Fwhm computation inverted in plot_psf_model and _compute_psf_model

### ISSUE THREAD

**Issue by mathtimm** [lgrcia/prose#49]
Using `obs._compute_psf_model() ` or `obs.plot_psf_model()` gives inverted values of `obs.stack.fwhmx` and `obs.stack.fwhmy`.

**Comment by lgrcia** [comment]
Not relevant to upcoming `3.0.0`, to be deleted when released

**Comment by lgrcia** [comment]
@mathtimm, did you solved it in [verse](https://github.com/mathtimm/verse)?

**Comment by lgrcia** [comment]
I close as it is outdated with version `3.x.x`
