### ISSUE TITLE
Add RA and DEC for selected star in summary plot

### ISSUE THREAD

**Issue by alexdumitriu** [lgrcia/prose#52]
I think it would be a nice idea if there would be a way to see the RA and DEC for the selected star in the summary plots. At the moment the RA and DEC on the summary plots are those from the centre of the image.

I see the following block of code (lines 1011-1018) in observation.py

`        params = [
            ("Telescope", f"{image.telescope.name}"),
            ("Date", f"{image.night_date}"),
            ("Filter", f"{image.filter}"),
            ("Exposure", f"{image.exposure}"),
            ("RA", f"{image.skycoord.ra:.4f}"),
            ("DEC", f"{image.skycoord.dec:.4f}"),
            ("Dimenion", f"{image.shape[0]}x{image.shape[1]} pixels"),`
           ]

I think it would be good to have the option to change the RA and DEC line from `skycoord.ra` and `skycoord.dec` to something like `stars_coords.ra` and `stars_coords.dec`

Many thanks,
Alex

**Comment by lgrcia** [comment]
Currently, version 3.0.0 will not support the `Observation` object anymore (too long to maintain). But there must be alternatives. I think a lot of features you require will be available in another package, [verse](https://github.com/mathtimm/verse), containing a nice interface with photometric measurements (like `Observation`) but this is in discussion.

**Comment by lgrcia** [comment]
I close that as it is outdated with the last version `3.x.x`. However I am happy yo have a new issue open to see how you can use the last version and what should be in `prose` and what should be in `verse`. 

Please do not hesitate (and note that `3.x.x` comes with great optimizations you might like, like multiprocessing)
