### ISSUE TITLE
prose 3.0.0 : problem installation on Windows (jaxlib)

### ISSUE THREAD

**Issue by hauretc** [lgrcia/prose#54]
It seems that Jaxlib (required to install prose 3.0.0) is not supported by Windows ( cfr https://stackoverflow.com/questions/62585395/not-able-to-install-jaxlib )

Possible solution: https://github.com/cloudhan/jax-windows-builder

**Comment by lgrcia** [comment]
I think you made changes @hauretc? Can you open a pull request?
