### ISSUE TITLE
how to add additional keyword to header when read fits file?

### ISSUE THREAD

**Issue by AlfredXiaSF** [lgrcia/prose#62]
When I read a fits file have no telescope information, and I want to add that manually, how can I do that?
I try this, but it not work:
```python
_ = Telescope(dict(name="A", keyword_observation_date="OBSTIME"))
fm = FitsManager(obs_path, extension='.fits', hdu=dict(TELESCOP='A'))
```
```python
----> [1](vscode-notebook-cell:/e%3A/03_Projects/ImageProcess/imlt/%E9%95%BF%E6%98%A5%E5%AE%9E%E6%B5%8B%E5%9B%BE%E5%83%8F%E5%A4%84%E7%90%86/prose.ipynb#W3sZmlsZQ%3D%3D?line=0) fm = FitsManager(obs_path, extension='.fits', hdu=dict(TELESCOP='A'))

File [c:\Users\Alfre\AppData\Local\Programs\Python\Python310\lib\site-packages\prose-2.3.1-py3.10.egg\prose\io\fitsmanager.py:76](file:///C:/Users/Alfre/AppData/Local/Programs/Python/Python310/lib/site-packages/prose-2.3.1-py3.10.egg/prose/io/fitsmanager.py:76), in FitsManager.__init__(self, folders, files, depth, hdu, extension, file, batch_size, scan, verbose, to_df)
     74 if files is not None:
     75     if len(files) > 0:
---> 76         self.scan_files(files, batch_size=batch_size, hdu=hdu, verbose=verbose)

File [c:\Users\Alfre\AppData\Local\Programs\Python\Python310\lib\site-packages\prose-2.3.1-py3.10.egg\prose\io\fitsmanager.py:192](file:///C:/Users/Alfre/AppData/Local/Programs/Python/Python310/lib/site-packages/prose-2.3.1-py3.10.egg/prose/io/fitsmanager.py:192), in FitsManager.scan_files(self, files, batch_size, verbose, hdu, telescope, verbose_new, verbose_os)
    190             "ERROR, batch ignored"
    191 else:
--> 192     df = self.fits_to_df(files_to_scan, verbose=True, hdu=hdu, verbose_os=verbose_os)
    193     for row in df.values:
    194         if telescope is not None:

File [c:\Users\Alfre\AppData\Local\Programs\Python\Python310\lib\site-packages\prose-2.3.1-py3.10.egg\prose\io\io.py:105](file:///C:/Users/Alfre/AppData/Local/Programs/Python/Python310/lib/site-packages/prose-2.3.1-py3.10.egg/prose/io/io.py:105), in fits_to_df(files, telescope_kw, instrument_kw, verbose, hdu, raise_oserror, verbose_os)
    103 for i in progress(files):
    104     try:
--> 105         header = fits.getheader(i, hdu)
    106     except OSError as err:
    107         if verbose_os:

File [c:\Users\Alfre\AppData\Local\Programs\Python\Python310\lib\site-packages\astropy\io\fits\convenience.py:103](file:///C:/Users/Alfre/AppData/Local/Programs/Python/Python310/lib/site-packages/astropy/io/fits/convenience.py:103), in getheader(filename, *args, **kwargs)
...
   1053         '(zero-indexed) or a (extname, extver) tuple.')
   1054 if extname is not None and not isinstance(extname, str):
   1055     raise ValueError('The extname argument must be a string.')

ValueError: The ext keyword must be either an extension number (zero-indexed) or a (extname, extver) tuple.
```

**Comment by lgrcia** [comment]
Right now the `FitsManager` looks for existing telescopes. There are many workarounds for that. One is to provide `FitsManager(to_fits=fits_to_df)` where `fits_to_df` is a function that outputs a Dataframe from reading a custom FITS file (that's how the headers are parsed). You can check the code of the default [`fits_to_df`](https://github.com/lgrcia/prose/blob/3.0.0/prose/io/io.py#L83) and make something for you need. Not great, I reckon....

The most straightforward thing is instead to add a feature allowing to do:
```python
telescope = Telescope(...)
fm = FitsManager(obs_path, extension='.fits', telescope=telescope)
```
I think it is a great feature. I am now implementing it and will let you now ASAP when its ready!

Thanks a lot for reporting this issue.

**Comment by lgrcia** [comment]
Done in [5ca5fdb](https://github.com/lgrcia/prose/commit/5ca5fdba084da10d640117376257f6a2122b6dff). You can let me know if that works.

**Comment by AlfredXiaSF** [comment]
> The most straightforward thing is instead to add a feature allowing to do:

@lgrcia  Think you! Great job!

The latest commit [466c945](https://github.com/lgrcia/prose/commit/466c945895e2fd66c23e64aa4702158ae5439b9d) works. But there is another problem, the time of my fits file is not in standard ISO format and lacks timezone information. I think it would be better if users could override the `date` method in `Telescope`.
```python
ParserError: Unknown string format: 2023:02:16:19:38:54.250
```
But for now, I work through the following:
```python
def date(header):
    header_date = header.get('OBSTIME', None)
    return datetime.strptime(header_date + '+00:00', '%Y:%m:%d:%H:%M:%S.%f%z')

telescope = Telescope(name="A", keyword_observation_date="OBSTIME")
telescope.date = date

fm = FitsManager(obs_path, extension='.fits', telescope=telescope)
```

**Comment by AlfredXiaSF** [comment]
And the same for `image_type`,
```python
def image_type(header):
    return 'light'

telescope = Telescope(name="A", keyword_observation_date="OBSTIME")
telescope.image_type = image_type
```

**Comment by AlfredXiaSF** [comment]
When I read a single fits file using the above telescope still causes time parse error:
```python
ref = FITSImage(fm.all_images[0], telescope=telescope)
```
I found it will parse time string in `FITSImage`, so I change 
```python
if image.metadata["jd"] is None:
    image.metadata["jd"] = Time(image.date).jd
```
to
```python
if image.metadata["jd"] is None:
    image.metadata["jd"] = Time(telescope.date(header)).jd
```

**Comment by lgrcia** [comment]
> I think it would be better if users could override the `date` method in `Telescope`

What about adding a `date_string_format` to the `Telescope` definition? so that if provided (not `None`) we parse 
```
datetime.strptime(header_date, self.date_string_format)
```
Your other change to `FITSImage` looks perfect! 👌🏼

Would you be interested in forking the project and making a pull request so that we can integrate your developments? (that would make you part of our next release paper!)

**Comment by AlfredXiaSF** [comment]
> What about adding a `date_string_format` to the `Telescope` definition? so that if provided (not `None`) we parse

Yes, it's a good choice.  

> Would you be interested in forking the project and making a pull request so that we can integrate your future developments? (that would make you part of our next release paper!)

With pleasure, if you don't mind my poor programming skills.
