### ISSUE TITLE
add sliding window sequence

### ISSUE THREAD

**Issue by AlfredXiaSF** [lgrcia/prose#68]
When I need to extract information from adjacent images, a standard `Sequence` class does not suffice. Therefore, I implemented a `SlidingSequence` class that inherits from `Sequence` and passes n images to the `_run()` function of blocks. This approach distinguishes between a current image and n-1 sliding window images.
This approach makes sense for extracting information from adjacent images.

To support the `SlidingSequence` class, I also added a `sliding` property to the `Block` class that indicates whether it is a sliding window block. These blocks require more than just the current image to operate.

In the `_run()` function, I execute all non-sliding window blocks first, followed by the sliding window blocks. This order of execution is important because some sliding window images may need preprocessing before passing to the sliding window blocks.

**Comment by lgrcia** [comment]
I think this has been discussed in #69
