### ISSUE TITLE
image.header vs image.fits_header

### ISSUE THREAD

**Issue by schackey** [lgrcia/prose#83]
There seems to be two attributes used for Image headers. One is 'image.header' as normally instantiated by an 'Image' object, and the other is 'image.fits_header', which is instantiated when using the 'FITSImage' object.
I recognised a problem, when I want to use the 'image.writeto()' function after having loaded an image using the 'FITSImage' object. The '.writeto()' function writes a header using the 'image.header' attribute, but when I load the image using the 'FITSImage' object, it only has the 'image.fits_header' attribute. And so in the end the written FITS file has no header (as it was seen as being empty).

I tried fixing the bug by renaming the fits_header attribute to the normal 'image.header' attribute, but some Blocks (like blocks.Get()) use the 'image.fits_header' attribute. So I decided to both declare the 'image.fits_header' and the 'image.header' attributes in the 'FITSImage' object for a possible fix.

## Code Sample
 def FITSImage(...)
       ...
    image = Image(values, metadata, {})
    if image.metadata["jd"] is None:
        image.metadata["jd"] = Time(image.date).jd
    image.fits_header = header ###################### PROBLEM
    image.header = header ######################### POSSIBLE FIX
    image.wcs = WCS(header)
    image.telescope = telescope

    return image

**Comment by lgrcia** [comment]
Thanks a lot for noticing that @schackey! I just created a fix that I will release as part of version 3.0.0. I'll close the issue once it is done and once the fix works as expected for you.

**Comment by lgrcia** [comment]
This will be part of `3.2.0`
